#端口号
server:
  port: 8080
#mybatis-plus
spring:
  application:
    # 应用的名字，该名字会被注册到注册中心，而且，该名字也是集群名字
    name: bath-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lianxi?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml #指定mapper.xml位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #输出sql日志
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler #枚举转换器

#Eureka配置
eureka:
  client:
    # 注册中心服务地址，你要向哪个注册中心注册
    service-url:
      defaultZone: http://localhost:8761/eureka/
    #当前应用是否注册到Eureka注册中心（默认就是true，因此无需配置）
    #    register-with-eureka: true
    #是否向Eureka注册中心拉取服务列表（默认就是true，因此无需配置）
#    fetch-registry: true
  instance:
    # 更倾向于使用ip，而不是host名，会注册本机所有的ip,默认是false使用主机名来注册。
    prefer-ip-address: true
    # ip地址 固定上报一个IP地址给eureka server，缺点只注册指定的
    #ip-address: 127.0.0.1
